/**
 * This file is auto-generated by . Please do not modify it manually.
 */
import { GetExampleEntityParams, GetExampleEntityQuery, GetExampleEntityResponse } from './types';

export interface GetExampleEntitySchemaType {
    Params: GetExampleEntityParams;
    Querystring: GetExampleEntityQuery;
    Reply: GetExampleEntityResponse;
}
export const GetExampleEntitySchema = {
    querystring: {
        type: 'object',
        properties: { include: { type: 'string', $schema: 'http://json-schema.org/draft-04/schema#' } },
    },
    params: {
        type: 'object',
        properties: { id: { type: 'integer', minimum: 1, $schema: 'http://json-schema.org/draft-04/schema#' } },
    },
};
