/* eslint-disable @typescript-eslint/no-empty-interface */

/**
 * This file is auto-generated by . Please do not modify it manually.
 */

export interface GetExampleEntityParams {
    id?: number;
}

export interface GetExampleEntityQuery {
    include?: string;
}

export type GetExampleEntityResponse =
    | {
          data: {
              /**
               * Id of entity
               */
              id: number;
          };
      }
    | {
          /**
           * Массив ошибок
           */
          errors: {
              /**
               * Строковый код ошибки
               */
              code: string;
              /**
               * Описание ошибки
               */
              message: string;
              /**
               * Объект с мета-информацией
               */
              meta?: {};
          }[];
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      };
