/* eslint-disable @typescript-eslint/no-empty-interface */

/**
 * This file is auto-generated by . Please do not modify it manually.
 */

export interface LogoutParams {}

export interface LogoutQuery {}

export type LogoutResponse =
    | {
          data: {};
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      }
    | {
          /**
           * Массив ошибок
           */
          errors: {
              /**
               * Строковый код ошибки
               */
              code: string;
              /**
               * Описание ошибки
               */
              message: string;
              /**
               * Объект с мета-информацией
               */
              meta?: {};
          }[];
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      };

export interface GetCurrentUserParams {}

export interface GetCurrentUserQuery {}

export type GetCurrentUserResponse =
    | {
          data: {
              /**
               * Идентификатор admin-пользователя
               */
              id?: number;
              /**
               * Полное ФИО
               */
              full_name?: string;
              /**
               * Сокращенное ФИО
               */
              short_name?: string;
              /**
               * Активен
               */
              active?: boolean;
              /**
               * Логин
               */
              login?: string;
              /**
               * Фамилия
               */
              last_name?: string;
              /**
               * Имя
               */
              first_name?: string;
              /**
               * Отчество
               */
              middle_name?: string;
              /**
               * Email
               */
              email?: string;
              /**
               * Телефон
               */
              phone?: string;
              /**
               * Роли пользователя
               */
              roles?: number[];
          };
          meta?: {};
      }
    | {
          /**
           * Массив ошибок
           */
          errors: {
              /**
               * Строковый код ошибки
               */
              code: string;
              /**
               * Описание ошибки
               */
              message: string;
              /**
               * Объект с мета-информацией
               */
              meta?: {};
          }[];
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      };

export interface LoginParams {}

export interface LoginQuery {}

export interface LoginBody {
    /**
     * Логин
     */
    login?: string;
    /**
     * Пароль
     */
    password?: string;
}

export type LoginResponse =
    | {
          data: {
              /**
               * Access Token
               */
              access_token?: string;
              /**
               * Refresh token
               */
              refresh_token?: string;
              /**
               * Время действия токена (в секундах)
               */
              expires_in?: number;
          };
      }
    | {
          /**
           * Массив ошибок
           */
          errors: {
              /**
               * Строковый код ошибки
               */
              code: string;
              /**
               * Описание ошибки
               */
              message: string;
              /**
               * Объект с мета-информацией
               */
              meta?: {};
          }[];
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      };

export interface RefreshParams {}

export interface RefreshQuery {}

export interface RefreshBody {
    /**
     * Refresh token
     */
    refresh_token?: string;
}

export type RefreshResponse =
    | {
          data: {
              /**
               * Access Token
               */
              access_token?: string;
              /**
               * Refresh token
               */
              refresh_token?: string;
              /**
               * Время действия токена (в секундах)
               */
              expires_in?: number;
          };
      }
    | {
          /**
           * Массив ошибок
           */
          errors: {
              /**
               * Строковый код ошибки
               */
              code: string;
              /**
               * Описание ошибки
               */
              message: string;
              /**
               * Объект с мета-информацией
               */
              meta?: {};
          }[];
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      };
