/**
 * This file is auto-generated by . Please do not modify it manually.
 */
import {
    DownloadProtectedFileBody,
    DownloadProtectedFileParams,
    DownloadProtectedFileQuery,
    DownloadProtectedFileResponse,
} from './types';

export interface DownloadProtectedFileSchemaType {
    Body: DownloadProtectedFileBody;
    Params: DownloadProtectedFileParams;
    Querystring: DownloadProtectedFileQuery;
    Reply: DownloadProtectedFileResponse;
}
export const DownloadProtectedFileSchema = {
    querystring: { type: 'object' },
    params: { type: 'object' },
    body: {
        type: 'object',
        description: 'Информация о файле в виде объекта. Для потребителя неважно какие внутри ключи',
    },
};
