/* eslint-disable @typescript-eslint/no-empty-interface */

/**
 * This file is auto-generated by . Please do not modify it manually.
 */

export interface DownloadProtectedFileParams {}

export interface DownloadProtectedFileQuery {}

/**
 * Информация о файле в виде объекта. Для потребителя неважно какие внутри ключи
 */
export interface DownloadProtectedFileBody {}

export type DownloadProtectedFileResponse =
    | string
    | {
          /**
           * Массив ошибок
           */
          errors: {
              /**
               * Строковый код ошибки
               */
              code: string;
              /**
               * Описание ошибки
               */
              message: string;
              /**
               * Объект с мета-информацией
               */
              meta?: {};
          }[];
          /**
           * Объект с мета-информацией
           */
          meta?: {};
      };
